# You can remove or add items in the default_cli_args permanently and then overwrite them by command line arguments.
# Note: `name`, `tolerations`, `affinity` are reserved variable names.
default_cli_args: 
  name: user-k8s-cli-test
  u: user
  nnodes:  1
  ngpus:  '0'
  ncpus:  '1'
  memory: 20Gi
  image: registry.sensetime.com/xlab/ding:zym-vpt-dev-v2
  tolerations:
  affinity: []
  command: |
    echo "Overwrite default command here by '--command'"

job_args:
- |
  # apt install ...
  eval $command


apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: ${default_cli_args.name}
  labels:
    u: ${default_cli_args.u}
spec:
  priority: normal
  backoffLimit: 0
  cleanPodPolicy: Running
  preemptible: false
  tasks:
  - replicas: ${default_cli_args.nnodes}
    type: none
    name: serial
    template:
      spec:
        tolerations:
        - key: "user"
          operator: "Equal"
          value: ${default_cli_args.tolerations}
          effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: ${default_cli_args.affinity}
        containers:
        - name: di-container
          image: ${default_cli_args.image}
          imagePullPolicy: IfNotPresent
          env:
          - name: PYTHONUNBUFFERED
            value: '1'
          - name: ngpus
            value: ${default_cli_args.ngpus}
          - name: ncpus
            value: ${default_cli_args.ncpus}
          - name: memory
            value: ${default_cli_args.memory}
          - name: command
            value: ${default_cli_args.command}
          resources:
            requests:
              nvidia.com/gpu-a100: ${default_cli_args.ngpus}
              cpu: ${default_cli_args.ncpus}
              memory: ${default_cli_args.memory}
            limits:
              nvidia.com/gpu-a100: ${default_cli_args.ngpus}
              cpu: ${default_cli_args.ncpus}
              memory: ${default_cli_args.memory}
          command: [/bin/bash, -c]
          args: ${job_args}
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
        volumes:
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
