# kubectl create -f test-ib.yml -n di --validate=false
default: 
  name: zzh-test
  u: zzh
  nnodes:  1
  ngpus:  '0'
  ncpus:  '1'
  memory: 20Gi
  image: registry.sensetime.com/xlab/ding:zym-vpt-dev-v2
  command: echo finished

args:
- |
  echo "build prerequisite"
  eval $command


apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: ${default.name}
  labels:
    u: ${default.u}
spec:
  priority: normal
  backoffLimit: 0
  cleanPodPolicy: Running
  preemptible: false
  tasks:
  - replicas: ${default.nnodes}
    type: none
    name: serial
    template:
      spec:
        containers:
        - name: di-container
          image: ${default.image}
          imagePullPolicy: IfNotPresent
          env:
          - name: PYTHONUNBUFFERED
            value: '1'
          - name: ngpus
            value: ${default.ngpus}
          - name: ncpus
            value: ${default.ncpus}
          - name: memory
            value: ${default.memory}
          - name: command
            value: ${default.command}
          resources:
            requests:
              nvidia.com/gpu-a100: ${default.ngpus}
              cpu: ${default.ncpus}
              memory: ${default.memory}
            limits:
              nvidia.com/gpu-a100: ${default.ngpus}
              cpu: ${default.ncpus}
              memory: ${default.memory}
          command: [/bin/bash, -c]
          args: ${args}
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: nfs-volume
            mountPath: /mnt/nfs/zhouzhanhui
          - name: share-volume
            mountPath: /mnt/nfs/share
        volumes:
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: nfs-volume
          hostPath:
            path: /mnt/nfs/zhouzhanhui
        - name: share-volume
          hostPath:
            path: /mnt/nfs/share
